# Generated by Django 4.2 on 2025-04-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('especialidade', models.CharField(choices=[('CAR', 'cardiologista'), ('ORT', 'ORTOPEDISTA'), ('GIN', 'Ginecologista')], max_length=3)),
                ('crm', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=30)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'agendado'), ('realizado', 'realizado'), ('cancelado', 'cancelado')], max_length=15)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
